# Generated by Django 5.1.3 on 2024-11-14 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("todos", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="todo",
            name="is_deleted",
            field=models.BooleanField(default=False),
        ),
    ]
